# Generated by Django 2.1.5 on 2019-02-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Trailer URL')),
                ('website', models.URLField(blank=True, help_text="The film's website", null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_year', models.PositiveSmallIntegerField()),
                ('running_time', models.PositiveSmallIntegerField(blank=True, help_text='Running time in minutes', null=True)),
                ('license_fees', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('licensing_notes', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='films.Category')),
                ('directors', models.ManyToManyField(blank=True, to='films.Director')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.Distributor')),
            ],
            options={
                'ordering': ['title', '-release_year'],
            },
        ),
    ]
