# Generated by Django 2.1.5 on 2019-02-10 01:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='licensing_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('last_name', 'first_name')},
        ),
    ]
