# Generated by Django 2.1.5 on 2019-02-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20190210_0109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('title', 'release_year')},
        ),
    ]
