# Generated by Django 2.1.5 on 2019-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20190210_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='status',
            name='ordering',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
