# Generated by Django 2.1.5 on 2019-02-10 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_film_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestor',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
