# Generated by Django 2.1.5 on 2019-02-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20190210_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_image',
        ),
    ]
