# Generated by Django 2.1.5 on 2019-02-16 01:19

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('films', '0010_remove_film_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
