# Generated by Django 2.1.5 on 2019-02-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_film_poster_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Statuses'},
        ),
    ]
