# Generated by Django 2.1.5 on 2019-02-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20190216_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
