# Generated by Django 2.1.5 on 2019-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190210_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelistExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(db_index=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Panelist Expertise',
            },
        ),
        migrations.AddField(
            model_name='panelist',
            name='expertise',
            field=models.ManyToManyField(blank=True, db_index=True, to='events.PanelistExpertise'),
        ),
    ]
