# Generated by Django 2.1.5 on 2019-02-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20190210_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Meaningful Movies Port Townsend Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
