# Generated by Django 2.2.3 on 2019-07-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_panelist_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='MMPT Admin Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
